### ISSUE TITLE
PingableConnection has been removed from doctrine/dbal since 3.0.0

### ISSUE THREAD

**Issue by andriusPr** [Cron/Symfony-Bundle#105]
Hello,

we are having some issues while using doctrine/dbal 3.0.0 (https://github.com/doctrine/dbal/pull/4128)
cron:run fails with error:

```
In Manager.php line 60:                                                                                        
Attempted to call an undefined method named "ping" of class "Doctrine\DBAL\Connection".
```

https://github.com/Cron/Symfony-Bundle/blob/master/Cron/Manager.php#L60
https://github.com/Cron/Symfony-Bundle/blob/master/Cron/Manager.php#L82

**Comment by gun-romainflamant** [comment]
Same thing for me, I propose a fix to the community

https://github.com/Cron/Symfony-Bundle/pull/108

**Comment by gun-romainflamant** [comment]
Fixed, Update Manager.php to fix DBAL3.0 incompatibility #108
