### ISSUE TITLE
Cron not working with Symfony 6.4

### ISSUE THREAD

**Issue by buczek93** [Cron/Symfony-Bundle#129]
Hi,
After updating application to symfony 6.4 we receive error. You can reproduce the error with any command for example: `bin console cron:list`. Bundle worked correctly with symfony 6.3. Details below:
 ```
Call to a member function getRepository() on null at /var/www/vendor/cron/cron-bundle/Cron/Manager.php:44)
```

Hotfix details:
We downgraded symfony/doctrine-bridge from version v7.0.0 to v6.4.0 and now it works.

**Comment by sookoll** [comment]
Same here. I don't have symfony/doctrine-bridge installed, so I have no clue, how to fix this.
