### ISSUE TITLE
Error - doctrine.orm.default_annotation_metadata_driver

### ISSUE THREAD

**Issue by sebastianpisula** [Cron/Symfony-Bundle#132]
I use `composer require cron/cron-bundle` command to install and I have error:

> The service "doctrine.orm.default_annotation_metadata_driver" has a dependency on a non-existent service "doctrine.orm.metadata.annotation_reader".

**Comment by SoufianLagnaoui** [comment]
if you try to install it on symfony 7 it will not works as it suppose to be. the package still uses annotations instead of attributes

**Comment by k0d3r1s** [comment]
will fix this in my PR later today. just hoping it will be merged soon too

**Comment by k0d3r1s** [comment]
@sebastianpisula can you check if it works with my PR code now? or maybe there needs to be fixes in dependencies as well (i can check this myself tomorrow probably)
