### ISSUE TITLE
Simplify usage of different entity manager

### ISSUE THREAD

**Issue by raphaelvoisin** [Cron/Symfony-Bundle#18]
I wished to use a separate database for cron usage, but the bundle currently use the `default` entity manager with something like:
- `$this->registry->getRepository('CronCronBundle:CronJob')`
- `$em = $this->registry->getManager();`
- ...

I ended to:
- override `cron.manager.class` with my own (`cron.manager.class: 'AppBundle\My\Cron\Manager'` in `parameters.yml`) extending your `Cron\CronBundle\Cron\Manager` class.
- override all methods that refers to default entity manager (`getJobRepo()`, `saveJob()`, `saveReports()`, `deleteJob()`).
`getJobRepo()` is handy:
I just replaced
`return $this->registry->getRepository('CronCronBundle:CronJob');`
by
`return $this->registry->getRepository('CronCronBundle:CronJob', 'my_cron_em');`
...but other ones need to be completely rewritten.

Am I missing a better solution ?

**Comment by NoUseFreak** [comment]
@raphaelvoisin Sorry for the delay!

Feel free to create a PR altering the constructor to something like 
```
function __construct(RegistryInterface $registry, , $persistentManagerName = null)
```

This way it is possible to inject from the container.
