### ISSUE TITLE
 The helper "dialog" is not defined Symfony3

### ISSUE THREAD

**Issue by elmaspicudo** [Cron/Symfony-Bundle#20]
[Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "dialog" is not defined.

**Comment by ianitsky** [comment]
Try update your bundle:

https://github.com/Cron/Symfony-Bundle/pull/14

**Comment by J-Safont** [comment]
Hello, we had the same issue with the release 3.0 and with dev-master it is fixed. It is possible to create a new version as is ? We need it in our project to be sustainable. 
Thank you very much !

**Comment by NoUseFreak** [comment]
Sorry for the late response. Tagged.
