### ISSUE TITLE
Unhardcode or extend string length or db collation in entities?

### ISSUE THREAD

**Issue by TrogWarZ** [Cron/Symfony-Bundle#22]
```php
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;
```

This will produce error if collation is not "utf8" (for me it is "utf8mb4_unicode_ci" in MariaDB):
`[Doctrine\DBAL\Driver\PDOException (42000)] SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

How can i extend default collation (i guess cron doesn't need utfmb4) or string length (needs to be 191 chars instead of 255)?

**Comment by dominikmank** [comment]
Your specific problem is solved with this: https://github.com/Cron/Symfony-Bundle/pull/23  isnt it?

**Comment by TrogWarZ** [comment]
@dominikmank, thank you – looks good! I'll really check it tomorrow.

**Comment by TrogWarZ** [comment]
Sorry about late answer. It's fixed, may be closed, thank you!
