### ISSUE TITLE
Cannot install under Symfony 4

### ISSUE THREAD

**Issue by sitya** [Cron/Symfony-Bundle#32]

**Comment by andreichirkunovgoon** [comment]
+1

**Comment by beloglazov91** [comment]
+1

**Comment by NoUseFreak** [comment]
I currently don't have any symfony 4 projects planned. Feel free to provide a Pull Request with the changes needed.

**Comment by NoUseFreak** [comment]
Fixed in `1.2.3` thanks to @kedramon
