### ISSUE TITLE
Commands not work in symfony 4

### ISSUE THREAD

**Issue by seddighi78** [Cron/Symfony-Bundle#35]
The command must set in service.yml file if not, commands not found in symfony 4 please update and fix it

**Comment by rbrlortie** [comment]
This should do the trick:


`\config\services.yaml`

    Cron\CronBundle\Command\CronCreateCommand:
        tags:
            - { name: 'console.command', command: 'cron:create' }
    Cron\CronBundle\Command\CronDeleteCommand:
        tags:
            - { name: 'console.command', command: 'cron:delete' }
    Cron\CronBundle\Command\CronDisableCommand:
        tags:
            - { name: 'console.command', command: 'cron:disable' }
    Cron\CronBundle\Command\CronEnableCommand:
        tags:
            - { name: 'console.command', command: 'cron:enable' }
    Cron\CronBundle\Command\CronListCommand:
        tags:
            - { name: 'console.command', command: 'cron:list' }
    Cron\CronBundle\Command\CronRunCommand:
        tags:
            - { name: 'console.command', command: 'cron:run' }
    Cron\CronBundle\Command\CronStartCommand:
        tags:
            - { name: 'console.command', command: 'cron:start' }
    Cron\CronBundle\Command\CronStopCommand:
        tags:
            - { name: 'console.command', command: 'cron:stop' }

**Comment by NoUseFreak** [comment]
@seddighi78 Thanks for filing the issue. Feel free to create a PR with the fix.
@rbrlortie Thanks for helping :-)
