### ISSUE TITLE
Commands running more often than they are supposed to, multiple output and tons of logs?

### ISSUE THREAD

**Issue by Emirii** [Cron/Symfony-Bundle#51]
Hi Everyone, I think I am either missing something with this bundle, or doing something wrong... 

I have a few jobs:
```
* * * * * Video Conversion Check
5 4 * * * Generate Sitemap
15 9 * * * Email Renewal Check
```

I started the command `php bin/console cron:start` in the background yesterday. 

Today there are 99 logs for Generate Sitemap job, which only should have been run once.  The sitemap output has the sitemap logs repeating 5 times (as if the command ran 5x before writing the log)... There are thousands of Video Conversion Check, in the log there is up to 10 logs for the same time for this job. It should be ran every minute but it looks like it is running 10 times per minute. The email renewal check should also be running once a day but has the same result as sitemap.

Run times are all negative and I'm not sure what that means. Surely my sitemap command is not taking hours to run? It takes maybe 4 seconds to run normally. 

This is what the job looks in my database:
id: 1
name: generate_sitemap 
command: job:daily:generateSitemap 
schedule: 5 4 * * *
description: Generates an updated sitemap daily.
enabled: 1

I have also noticed increased CPU usage with the cron command running.

**Comment by Emirii** [comment]
I set `Video Conversion Check` to run at :30 of every hour (`30 * * * *`). The command continues to run over and over again every minute after the scheduled time, appending the output logs. How do I stop this behavior so that it only runs once?

![image](https://user-images.githubusercontent.com/6307976/52069071-a010c180-2543-11e9-89ec-6f36738db4cb.png)

**Comment by RiseAndCry** [comment]
+1

**Comment by NoUseFreak** [comment]
@Emirii Sorry for the delay, could you provide a failing test, that helps a lot to debug the issue.

**Comment by RiseAndCry** [comment]
I just downloaded 2.0.2 version.
Used `cron:create` command (after necessary prerequisites) and ran `cron:start`. That's it.
The cron did work and start outputting reports every minute, but they started increasing with every iteration.
I'm sorry, i can't write tests at the moment, but it should be fairly easy to catch this bug.

**Comment by apeto-techteamer** [comment]
I can confirm the same bug: 
the reports are stored in the Executor class' "sets" variable which is not cleared after each run (in daemon mode) and the new reports are appended. 
That's why it is increasing.

**Comment by NoUseFreak** [comment]
I believe I found the issue in the core library.
I believe it is fixed in https://github.com/Cron/Cron/pull/58. 

Could you run `composer update cron/cron` and verify the fix?

**Comment by NoUseFreak** [comment]
Going to close the issue. Please re-open if it's not fixed
