### ISSUE TITLE
job schedule is not properly reloaded from DB on change

### ISSUE THREAD

**Issue by apeto-techteamer** [Cron/Symfony-Bundle#52]
hi,

if you start cron with cron:start --blocking, then the records from db are not reloaded even if they changed after starting the command, because the entity manager take care of it.
it's a problem, because no other process can change schedules if the cron process already started or without restarting it.

steps to reproduce:
* add a job with * * * * * schedule
* start bin/console cron:start --blocking
* wait for the first run
* check that the job was started
* change the schedule of the job in db to anything
* wait for the next run
* check if the job was "rescheduled"

As I experienced, no mather what I change, in the variables the original schedule appear.

If I add `$this->registry->getEntityManager()->clear();` to Manager.php:78 to the beginning of the function `listEnabledJobs` it reloads well.

**Comment by NoUseFreak** [comment]
Fixed in v2.0.3
