### ISSUE TITLE
Deprecated use of ContainerAwareCommand since Symfony 4.2

### ISSUE THREAD

**Issue by DerDu** [Cron/Symfony-Bundle#58]
In Symfony 4.2 you get the following warning:

> The "Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand" class is deprecated since Symfony 4.2, use "Symfony\Component\Console\Command\Command" with dependency injection instead.

This happens because of extending ContainerAwareCommand for _cron_ commands
Please change it to use/respect the new approach

**Comment by yahyaerturan** [comment]
+1

**Comment by janklan** [comment]
@NoUseFreak I'm wondering if you'll merge a PR & release a new version if I take care of this?

**Comment by NoUseFreak** [comment]
@janklan Yes, I haven't had time to get to the issues, but if a PR get's provided with working tests, a merge should be fine. 

Please also let me know if the change will be backwards compatible.

**Comment by gabrielspiteri-highlight** [comment]
@NoUseFreak I have created a PR for this issue. Let me know if you need something more.

**Comment by NoUseFreak** [comment]
Fixed in 2.2.0

**Comment by gabrielspiteri-highlight** [comment]
Wow thanks :) will pull the new tag to our project.

**Comment by DerDu** [comment]
Thanks :)
