### ISSUE TITLE
Problem install cron/cron-bundle. Symfony 5.0.1

### ISSUE THREAD

**Issue by Antonpc** [Cron/Symfony-Bundle#68]
composer require cron/cron-bundle
Using version ^2.2 for cron/cron-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cron/cron-bundle ^2.2 -> satisfiable by cron/cron-bundle[2.2.0].
    - cron/cron-bundle 2.2.0 requires symfony/framework-bundle ^3.4|^4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by vaibhavpandeyvpz** [comment]
I am also willing to use this bundle with 5.0. Any update from maintainers? @NoUseFreak

**Comment by NoUseFreak** [comment]
@vaibhavpandeyvpz I've added a tag to allow installations on ^5.0. Can you let me know how it goes?
