### ISSUE TITLE
Preserve environment when running jobs

### ISSUE THREAD

**Issue by malaney** [Cron/Symfony-Bundle#7]
Firstly, thanks for publishing an awesome tool for managing cron jobs!!  It has really helped simplify my workflow.  I've come across a situation where I'd like to be able to run the same cron jobs in both staging as well as production environments.  Ideally, I'd like to be able to set up a cron job with /usr/bin/php app/console cron:run --env=staging and have it run all enabled crons with the --env=staging switch added and /usr/bin/php app/console cron:run --env=prod and have it run all enabled crons with the --env=prod switch added.  If I can have the environment flag carried across to my jobs then I won't have to specify the environment on my individual cron jobs.

**Comment by NoUseFreak** [comment]
@malaney Thanks you for the issue. 

I just added a fix that should fix your problem. Can you verify this solves your issue. If so I will tag this as the first stable release.

**Comment by malaney** [comment]
This appears to work perfectly!  Thanks for addressing so quickly.
