### ISSUE TITLE
Prevent Running Of Duplicate Cron Jobs

### ISSUE THREAD

**Issue by arturturundaev** [Cron/Symfony-Bundle#73]
Hello!
First of all, thanks you for your bundle! It's awesome!

But I have one question:
How can I disable starting the script if the previous one still works?

I used console bin/console cron:create to add new script.
And when I put in "Command:" /usr/bin/flock -w 0 /var/tmp/file.lock command, but I resived error message "The command "/usr/bin/flock" does not exist."

In console I can exec /usr/bin/flock.

**Comment by xorik** [comment]
Symfony have built-in locking mechanism:
https://symfony.com/doc/current/components/lock.html

**Comment by arturturundaev** [comment]
Ok, it's a solution to my problem, but why I can exec more than 1 example of "bin/console cron:start"?
```
ps aux | grep "[p]hp bin/console cron:start"
user      2709  0.7  0.1 103308 29828 ?        Ss   10:00   0:01 php bin/console cron:start
user      2755  2.4  0.1 103308 29732 ?        Ss   10:03   0:00 php bin/console cron:start
user      2760  2.2  0.1 103308 29632 ?        Ss   10:03   0:00 php bin/console cron:start
```

**Comment by xorik** [comment]
@arturturundaev because this command doesn't have locking
