### ISSUE TITLE
Cron job will not execute with another schedule

### ISSUE THREAD

**Issue by legalvisio** [Cron/Symfony-Bundle#78]
With this __30 6 * * 1-5__  schedule the cron job will not execute.
As test I set it on my current time, for example __39 13 * * 1-5__ and it works.

Another example is the this schedule __* * * * *__ works, but not __*/5 * * * *__ or __*/2 * * * *__
Whats here the problem?

**Comment by legalvisio** [comment]
> With this **30 6 * * 1-5** schedule the cron job will not execute.
> As test I set it on my current time, for example **39 13 * * 1-5** and it works.
> 
> Another example is the this schedule *** * * * *** works, but not ***/5 * * * *** or ***/2 * * * ***
> Whats here the problem?

**Comment by legalvisio** [comment]
In dev environment with small processes it works well.
But on prod environment with big processes, only schedules like __* * * * *__  are working.

**Comment by NoUseFreak** [comment]
@legalvisio Are you able to manipulate a test to stage such an issue?

**Comment by legalvisio** [comment]
No not really.
The cron jobs with schedule interval __*/5 * * * *__ is working now.
I think some commands had a problem, and all other cron jobs with schedule interval were not execute.
With this schedule __30 11,16 * * *__ __0 8,15,17 * * *__ __0 6 * * *__ I have still problem to call.
When I start this command manually like __bin/console cron:run JOB_NAME__ it's not listet in DB table cron_report.
