### ISSUE TITLE
Can we extend repositories from ServiceEntityRepository class instead of EntityRepository class?

### ISSUE THREAD

**Issue by modiniks** [Cron/Symfony-Bundle#79]
Can we upgrade to 

class CronJobRepository extends ServiceEntityRepository
class CronReportRepository extends ServiceEntityRepository

instead of

class CronJobRepository extends EntityRepository
class CronReportRepository extends EntityRepository

ServiceEntityRepository class extends from EntityRepository class.
ManagerRegistry class is injected in the ServiceEntityRepository class constructor.
This can help in reducing code in Cron Manager where we are injecting ManagerRegistry and getting repositories.

**Comment by NoUseFreak** [comment]
Hi @modiniks, we can indeed do this. Do you know if it will be a breaking change or from what version this is possible?
