### ISSUE TITLE
Cron:run uses missing Doctrine class

### ISSUE THREAD

**Issue by link365dev** [Cron/Symfony-Bundle#80]
When trying to execute:
`
$ php /var/www/bin/console cron:run

In Manager.php line 31:

  Argument 1 passed to Cron\CronBundle\Cron\Manager::__construct() must be an instance of Doctrine\Persistence\ManagerRegistry, instance of D
  octrine\Bundle\DoctrineBundle\Registry given, called in /var/www/var/cache/dev/ContainerLtkPqt8/getCron_ManagerService.php on line 11

cron:run [--force] [--schedule_now] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<job>]
`

**Comment by link365dev** [comment]
Findings:

In class:
`
namespace Cron\CronBundle\Cron;

use Cron\CronBundle\Entity\CronJob;
use Cron\CronBundle\Entity\CronJobRepository;
use Cron\CronBundle\Entity\CronReport;
**use Doctrine\Persistence\ManagerRegistry;**
use Cron\Report\JobReport;

/**
 * @author Dries De Peuter <dries@nousefreak.be>
 */
class Manager
{
`

**Doctrine\Persistence\ManagerRegistry** should be replaced with **Symfony\Bridge\Doctrine\ManagerRegistry**

**Comment by stevecohenfr** [comment]
I fixed it by installing old version :

    require cron/cron-bundle:2.2.0

**Comment by link365dev** [comment]
@stevecohenfr But the old version has some deprecation warnings. Our team is trying to use the new version to remove all the deprecation warnings from our app.

**Comment by wuturk91** [comment]
Try specifying CronCronBundle() within the mappings for orm within your config.yml? Also check which Doctrine-Bundle version your using which can be limited by your PHP version.
