### ISSUE TITLE
Memory Limit

### ISSUE THREAD

**Issue by wiseguy1394** [Cron/Symfony-Bundle#84]
We run our Cron command with php -d memory_limit=4096M, but the subprocess run with the default memory_limit of the server. Is there any possibility to change the memory_limit for subprocesses ?

The symfony Process supports the following: --define memory_limit=4096

**Comment by NoUseFreak** [comment]
I think we can enable this by allowing the `CommandBuilder` to allow defining a `memory_limit` using DI.

**Comment by wouter-toppy** [comment]
@NoUseFreak  ive created a pull #94

**Comment by NoUseFreak** [comment]
@wouter-toppy Thanks for the contrib.
Changes are released under version 2.6.0
