### ISSUE TITLE
Problem with entities

### ISSUE THREAD

**Issue by UnknownNewUser** [Cron/Symfony-Bundle#88]
Hi,
I tried to integrate this bundle in a project which I am working on and everything is seems to be ok except when we try to interact with database,

The error messsage is:
```
An exception occurred while executing 'SELECT cron_job_id_seq.nextval FROM DUAL':                                                                   
ORA-02289: sequence does not exist                                                 
In OCI8Exception.php line 23:
                                      
ORA-02289: sequence does not exist  
```
And for info, the sequence **cron_job_id_seq** exist in database.

For info, we are using Oracle database and we use different schemas:
Schema 1 which include tables and views
Schema 2 which has some privileges on some tables and views in schema 1
And our application use schema 2 to connect to the database

The problem is already identified by us but we didn't find a solution to solve it without touching the entities in the bundle,
The similar problem is explained in this link:
https://stackoverflow.com/questions/25726573/sequence-doesnt-exist-ora-02289/25726744

The solution is to replace this line in the entity file:
`@ORM\GeneratedValue(strategy="AUTO")`
With:
```
@ORM\GeneratedValue(strategy="SEQUENCE")
@ORM\SequenceGenerator(sequenceName="schema 1.cron_job_id_seq", allocationSize=1, initialValue=1)
```
I also include some screenshots that might help to better understand the problem.

![01](https://user-images.githubusercontent.com/77053289/103762614-e49f1480-5018-11eb-9569-b7683ede9491.png)
![02](https://user-images.githubusercontent.com/77053289/103762619-e537ab00-5018-11eb-8bbe-1382fb3d6ad1.png)

It will be nice if you will be able to provide a solution to solve this problem,
Thank you in advance.

**Comment by NoUseFreak** [comment]
Hi @UnknownNewUser, I've never validated if it works against Oracle, only MySQL was tested as far as I know.
I'm not able to help with oracle related issues due to a lack of knowledge.

**Comment by tocw86** [comment]
Try to create those sequence in Oracle sql manager, maybe this helps you:

`CREATE SEQUENCE cron_job_seq START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER cron_job_seq_tr
 BEFORE INSERT ON cron_job FOR EACH ROW
 WHEN (NEW.id IS NULL)
BEGIN
 SELECT cron_job_seq.NEXTVAL INTO :NEW.id FROM DUAL
END`
