### ISSUE TITLE
Provide a command to truncate cron reports

### ISSUE THREAD

**Issue by dsentker** [Cron/Symfony-Bundle#99]
I run some cron jobs every minute. Within a few days I had accumulated 100 MB of database logs. It would make sense if one could automatically truncate the cron report table, e.g.
```bash
bin/console cron:reports:truncate +72
```
(Would delete every report older than 72h).

If there is interest, I could also do a PR.

**Comment by wouter-toppy** [comment]
See #102

**Comment by wouter-toppy** [comment]
@NoUseFreak See Pull
